# SPDX-FileCopyrightText: © 2025, 2026 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Cache"

on:
  push:
    branches:
      - "main"
  # Weekly refresh, so unused caches are not evicted (7 days)
  schedule:
    - cron: "0 3 * * 6"
  workflow_dispatch:

# enq: the only way to set permissions to none in GH Actions
permissions: {} # yamllint disable-line rule:braces

cache-mode: "write"

concurrency:
  group: >
    ${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cache:
    name: "Cache"
    # Skip initial commit
    if: >
      github.event.head_commit.message != 'Initial commit'
    permissions:
      contents: "read"
    uses: "$/.github/workflows/cache-reusable.yml"
...
