# SPDX-FileCopyrightText: © 2025 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Code"

on:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "DCO.md"
      - "docs/DCO.md"
      - "LICENSE.md"
      - "docs/LICENSE.md"
      - "LICENSES/*"
  merge_group:
    types:
      - "checks_requested"

permissions: {} # yamllint disable-line rule:braces

concurrency:
  group: >
    ${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code:
    name: "Code"
    permissions:
      contents: "read"
    # yamllint disable rule:line-length
    uses: "./.github/workflows/code-reusable.yml"
    # yamllint enable rule:line-length
...
