# SPDX-FileCopyrightText: © 2025, 2026 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "GitHub Actions Reusable"

on:
  workflow_call:

# enq: the only way to set permissions to none in GH Actions
permissions: {} # yamllint disable-line rule:braces

jobs:
  github-actions-reusable:
    name: "GitHub Actions Reusable"
    permissions:
      contents: "read"
    uses: "$/.github/workflows/run-check-reusable.yml"
    with:
      check: "github-actions"
      arguments: ".github/actions/*/action.yml"
      group: "github"
      sparse-checkout: |
        .github/actions/*/action.yml
...
