# SPDX-FileCopyrightText: © 2025, 2026 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
# enq: reusable workflows offload concurrency limits to the caller
name: "Latest Release SHA Reusable"  # zizmor: ignore[concurrency-limits]

on:
  workflow_call:
    outputs:
      ref:
        description: "The latest release commit SHA."
        value: "${{ jobs.latest-release.outputs.ref }}"

# enq: the only way to set permissions to none in GH Actions
permissions: {} # yamllint disable-line rule:braces

jobs:
  latest-release:
    name: "Latest Release"
    timeout-minutes: 10
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
    outputs:
      ref: "${{ steps.latest-release.outputs.ref }}"
    steps:
      - name: "Harden Runner"
        # enq: hash with name and version always longer than 80 chars
        # yamllint disable rule:line-length
        uses: "step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594" # v2.16.0
        # yamllint enable rule:line-length
        with:
          disable-sudo-and-containers: true
          egress-policy: "block"
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            raw.githubusercontent.com:443
            objects.githubusercontent.com:443
            release-assets.githubusercontent.com:443
      - name: "Get latest release ref"
        id: "latest-release"
        # enq: hash with name and version always longer than 80 chars
        # yamllint disable rule:line-length
        # enq: unpinned as it allows projects to use the latest
        uses: "open-nudge/opentemplate/.github/actions/release-ref@main" # zizmor: ignore[unpinned-uses]
        # yamllint enable rule:line-length
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
...
