# SPDX-FileCopyrightText: © 2025, 2026 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Policy"

on:
  pull_request:
    branches:
      - "main"
  merge_group:
    types:
      - "checks_requested"

# enq: the only way to set permissions to none in GH Actions
permissions: {} # yamllint disable-line rule:braces

concurrency:
  group: >
    ${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  policy:
    timeout-minutes: 10
    name: "Policy"
    permissions:
      contents: "read"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Harden Runner"
        # enq: hash with name and version always longer than 80 chars
        # yamllint disable rule:line-length
        uses: "step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1" # v2.21.1
        # yamllint enable rule:line-length
        with:
          # Uses docker container,
          # disable-sudo-and-containers impossible
          disable-sudo: true
          egress-policy: "block"
          allowed-endpoints: >
            *.actions.githubusercontent.com:443
            codeload.github.com:443
            results-receiver.actions.githubusercontent.com:443
            *.blob.core.windows.net:443
            api.github.com:443
            github.com:443
      - name: "Checkout Repository"
        # enq: hash with name and version always longer than 80 chars
        # yamllint disable rule:line-length
        uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1
        # yamllint enable rule:line-length
        with:
          sparse-checkout: |
            .conform.yaml
          sparse-checkout-cone-mode: false
          persist-credentials: false
          # Necessary for the conform action to work (commit ranges)
          # See here: https://github.com/siderolabs/conform/issues/231
          fetch-depth: 2
      - name: "Check policy compliance"
        # enq: hash with name and version always longer than 80 chars
        # yamllint disable rule:line-length
        uses: "siderolabs/conform@cfdb3cce90daece912e6a5cb3f20b2316a78a5bf" # v0.1.0-alpha.31
        # yamllint enable rule:line-length
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
...
