# SPDX-FileCopyrightText: © 2025, 2026 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Prose"

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "**.md"
      - "**.py"
      - "**.sh"
      - "!LICENSE"
      - "!docs/LICENSE.md"
      - "!LICENSES/*"
      - ".github/workflows/prose.yml"
  merge_group:
    types:
      - "checks_requested"

# enq: the only way to set permissions to none in GH Actions
permissions: {} # yamllint disable-line rule:braces

concurrency:
  group: >
    ${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prose:
    name: "Prose"
    permissions:
      contents: "read"
    timeout-minutes: 10
    runs-on: "ubuntu-latest"
    steps:
      - name: "Harden Runner"
        # enq: hash with name and version always longer than 80 chars
        # yamllint disable rule:line-length
        uses: "step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1" # v2.21.1
        # yamllint enable rule:line-length
        with:
          disable-sudo: true
          # enq: cannot reliably prevent and inspect docker steps egress
          egress-policy: "audit"
      - name: "Checkout repository"
        # enq: hash with name and version always longer than 80 chars
        # yamllint disable rule:line-length
        uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1
        # yamllint enable rule:line-length
        with:
          persist-credentials: false
      - name: "Sync Vale packages"
        # enq: the image reference is digest-pinned.
        # yamllint disable rule:line-length
        uses: "docker://docker.io/jdkato/vale:v3.20.0@sha256:5a2852baf6332a2beb2aa187aa4828ce600b0368720e338f8ea8521cdb826a1d"
        # yamllint enable rule:line-length
        with:
          args: "sync"
      - name: "Check prose with Vale"
        # enq: the image reference is digest-pinned.
        # yamllint disable rule:line-length
        uses: "docker://docker.io/jdkato/vale:v3.20.0@sha256:5a2852baf6332a2beb2aa187aa4828ce600b0368720e338f8ea8521cdb826a1d"
        # yamllint enable rule:line-length
        with:
          args: "--glob=!{LICENSE,LICENSES/**} ."
      - name: "Check for generated changes"
        run: "git diff --exit-code"
...
