# SPDX-FileCopyrightText: © 2025, 2026 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "pyproject Reusable"

on:
  workflow_call:

# enq: the only way to set permissions to none in GH Actions
permissions: {} # yamllint disable-line rule:braces

jobs:
  pyproject-reusable:
    name: "pyproject Reusable"
    permissions:
      contents: "read"
    uses: "$/.github/workflows/run-check-reusable.yml"
    with:
      check: "pyproject"
...
