# SPDX-FileCopyrightText: © 2025, 2026 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Security SBOM GitHub Update"

on:
  schedule:
    - cron: "0 3 * * 6"
  workflow_dispatch:
# enq: the only way to set permissions to none in GH Actions
permissions: {} # yamllint disable-line rule:braces

jobs:
  security-sbom-github-update:
    permissions:
      actions: "read" # https://github.com/github/codeql-action/issues/2117
      security-events: "write" # Needed to upload SARIF file to tab
      contents: "read"
      id-token: "write" # Needed to get GH Token to attest
      attestations: "write" # Needed to upload attestation
    name: "Security SBOM GitHub Update"
    # enq: hash with name and version always longer than 80 chars
    # yamllint disable rule:line-length
    # enq: unpinned as it allows projects to use the latest
    uses: "open-nudge/opentemplate/.github/workflows/security-sbom-github-reusable.yml@main" # zizmor: ignore[unpinned-uses]
    # yamllint enable rule:line-length
    with:
      upload-artifact: true
      upload-grype-artifact: true
      upload-grype-sarif: true
...
